cat /tmp/talib_yf_pygame.dec.09.2025.environment.yml 
name: talib_yf_pygame
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - alsa-lib=1.2.14=hb9d3cd8_0
  - altair=5.5.0=pyhd8ed1ab_1
  - aom=3.9.1=hac33072_0
  - appdirs=1.4.4=pyhd8ed1ab_1
  - attr=2.5.2=h39aace5_0
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.9.0=h9a6e2ae_4
  - aws-c-cal=0.9.0=hada3f3f_0
  - aws-c-common=0.12.2=hb9d3cd8_0
  - aws-c-compression=0.3.1=hc2d532b_4
  - aws-c-event-stream=0.5.4=hc5e5e9e_7
  - aws-c-http=0.10.0=h6884c39_0
  - aws-c-io=0.18.1=h1a9f769_2
  - aws-c-mqtt=0.12.3=hef6a231_4
  - aws-c-s3=0.7.16=h7dfd680_1
  - aws-c-sdkutils=0.2.3=hc2d532b_4
  - aws-checksums=0.2.7=hc2d532b_0
  - aws-crt-cpp=0.32.4=h0cee55f_2
  - aws-sdk-cpp=1.11.510=h5b777a2_6
  - azure-core-cpp=1.14.0=h5cfcd09_0
  - azure-identity-cpp=1.10.0=h113e628_0
  - azure-storage-blobs-cpp=12.13.0=h3cf044e_1
  - azure-storage-common-cpp=12.8.0=h736e048_1
  - azure-storage-files-datalake-cpp=12.12.0=ha633028_1
  - beautifulsoup4=4.13.4=pyha770c72_0
  - blinker=1.9.0=pyhff2d567_0
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.1.0=py312h2ec8cdc_2
  - bzip2=1.0.8=h4bc722e_7
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.11.12=hbd8a1cb_0
  - cachetools=5.5.2=pyhd8ed1ab_0
  - cairo=1.18.4=h3394656_0
  - certifi=2025.11.12=pyhd8ed1ab_0
  - cffi=1.17.1=py312h1fdaa30_1
  - charset-normalizer=3.4.2=pyhd8ed1ab_0
  - click=8.1.8=pyh707e725_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - contourpy=1.3.2=py312h68727a3_0
  - cpython=3.12.10=py312hd8ed1ab_0
  - curl-cffi=0.10.0=py312h53d9707_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.27=h54b06d7_7
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - double-conversion=3.3.1=h5888daf_0
  - et_xmlfile=2.0.0=pyhd8ed1ab_1
  - expat=2.7.0=h5888daf_0
  - fluidsynth=2.3.7=hd992666_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.57.0=py312h178313f_0
  - fpdf=1.7.2=pyhd8ed1ab_0
  - fredapi=0.5.2=pyhd8ed1ab_0
  - freetype=2.13.3=ha770c72_1
  - frozendict=2.4.6=py312h66e93f0_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - gflags=2.2.2=h5888daf_1005
  - gitdb=4.0.12=pyhd8ed1ab_0
  - gitpython=3.1.44=pyhff2d567_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py312h7201bc8_0
  - graphite2=1.3.14=h295c915_1
  - h2=4.2.0=pyhd8ed1ab_0
  - harfbuzz=11.1.0=h3beb420_0
  - hmmlearn=0.3.3=py312h1289d80_1
  - hpack=4.1.0=pyhd8ed1ab_0
  - html5lib=1.1=pyhd8ed1ab_2
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - imageio=2.37.0=pyhfb79c49_0
  - importlib-metadata=8.6.1=pyha770c72_0
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - jack=1.9.22=hf4617a5_3
  - jinja2=3.1.6=pyhd8ed1ab_0
  - joblib=1.4.2=py312h06a4308_0
  - jsonschema=4.23.0=pyhd8ed1ab_1
  - jsonschema-specifications=2025.4.1=pyh29332c3_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.8=py312h84d6215_0
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - lerc=4.0.0=h0aef613_1
  - libabseil=20250127.1=cxx17_hbbce691_0
  - libarrow=20.0.0=h27f8bab_0_cpu
  - libarrow-acero=20.0.0=hcb10f89_0_cpu
  - libarrow-dataset=20.0.0=hcb10f89_0_cpu
  - libarrow-substrait=20.0.0=h1bed206_0_cpu
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libavif16=1.3.0=h6395336_2
  - libblas=3.9.0=31_h59b9bed_openblas
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcap=2.76=h0b2e76d_0
  - libcblas=3.9.0=31_he106b2a_openblas
  - libclang-cpp20.1=20.1.4=default_h1df26ce_0
  - libclang13=20.1.4=default_he06ed0a_0
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.13.0=h332b0f4_0
  - libdeflate=1.23=h86f0d12_0
  - libdrm=2.4.124=hb9d3cd8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_2
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.6=h2dba641_1
  - libflac=1.4.3=h59595ed_0
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=14.2.0=h69a702a_2
  - libgfortran5=14.2.0=hf1ad2bd_2
  - libgl=1.7.0=ha4b6fd6_2
  - libglib=2.84.1=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_2
  - libglx=1.7.0=ha4b6fd6_2
  - libgomp=14.2.0=h767d61c_2
  - libgoogle-cloud=2.36.0=hc4361e1_1
  - libgoogle-cloud-storage=2.36.0=h0121fbd_1
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.71.0=h8e591d7_1
  - libiconv=1.18=h4ce23a2_1
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=31_h7ac8fdf_openblas
  - libllvm20=20.1.4=he9d0ab4_0
  - liblzma=5.8.1=hb9d3cd8_1
  - libmad=0.15.1b=h0b41bf4_1001
  - libnghttp2=1.64.0=h161d5f1_0
  - libnsl=2.0.1=hd590300_0
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libopengl=1.7.0=ha4b6fd6_2
  - libopentelemetry-cpp=1.20.0=hd1b1c89_0
  - libopentelemetry-cpp-headers=1.20.0=ha770c72_0
  - libopus=1.5.2=hd0c01bc_0
  - libparquet=20.0.0=h081d1f1_0_cpu
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.47=h943b412_0
  - libpq=17.4=h27ae623_1
  - libprotobuf=5.29.3=h501fc15_1
  - libre2-11=2024.07.02=hba17884_3
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.49.1=hee588c1_2
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=14.2.0=h8f9b012_2
  - libstdcxx-ng=14.2.0=h4852527_2
  - libsystemd0=257.9=h996ca69_0
  - libta-lib=0.4.0=hd590300_2
  - libthrift=0.21.0=h0e7cc3e_0
  - libtiff=4.7.0=hd9ff511_4
  - libudev1=257.9=h085a93f_0
  - libunwind=1.6.2=h9c3ff4c_0
  - liburing=2.9=h84d6215_0
  - libusb=1.0.29=h73b1eb8_0
  - libutf8proc=2.10.0=h4c51ac1_0
  - libuuid=2.38.1=h0b41bf4_0
  - libvorbis=1.3.7=h54a6638_2
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.9.1=h65c71a3_0
  - libxml2=2.13.7=h4bc477f_1
  - libxslt=1.1.41=h097e994_0
  - libzlib=1.3.1=hb9d3cd8_2
  - lxml=5.4.0=py312h68d7fa5_0
  - lz4-c=1.10.0=h5888daf_1
  - markupsafe=3.0.2=py312h178313f_1
  - matplotlib=3.10.1=py312h7900ff3_0
  - matplotlib-base=3.10.1=py312hd3ec401_0
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mplfinance=0.12.9b7=pyhd8ed1ab_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multitasking=0.0.9=pyhd8ed1ab_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - mysql-common=9.2.0=h266115a_0
  - mysql-libs=9.2.0=he0572af_0
  - narwhals=1.38.0=pyhe01879c_0
  - ncurses=6.5=h2d0b736_3
  - nlohmann_json=3.12.0=h3f2d84a_0
  - numpy=2.2.5=py312h72c5963_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openldap=2.6.9=he970967_0
  - openpyxl=3.1.5=py312h710cb58_1
  - openssl=3.6.0=h26f9b46_0
  - opusfile=0.12=h3358134_2
  - orc=2.1.1=h17f744e_1
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py312hf9745cd_3
  - patsy=1.0.1=pyhd8ed1ab_1
  - pcre2=10.44=hc749103_2
  - peewee=3.18.1=py312ha6a020b_0
  - pillow=11.1.0=py312h80c1187_0
  - pip=25.1.1=pyh8b19718_0
  - pixman=0.46.0=h29eaf8c_0
  - pkgutil-resolve-name=1.3.10=pyhd8ed1ab_2
  - platformdirs=4.3.7=pyh29332c3_0
  - plotly=6.0.1=pyhd8ed1ab_0
  - portaudio=19.6.0=h7c63dc7_9
  - portmidi=2.0.6=hf4617a5_0
  - prometheus-cpp=1.3.0=ha5d0236_0
  - protobuf=5.29.3=py312h0f4f066_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pulseaudio-client=17.0=hac146a9_1
  - pyarrow=20.0.0=py312h7900ff3_0
  - pyarrow-core=20.0.0=py312h01725c0_0_cpu
  - pycparser=2.22=pyh29332c3_1
  - pygame=2.6.1=py312h4fcb14b_0
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyside6=6.9.0=py312h91f0f75_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.10=h9e4cc4f_0_cpython
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=7_cp312
  - pytz=2025.2=pyhd8ed1ab_0
  - pywavelets=1.9.0=py312h4f23490_2
  - pyyaml=6.0.2=py312h178313f_2
  - qhull=2020.2=h434a139_5
  - qt6-main=6.9.0=h6441bc3_1
  - rav1e=0.7.1=h8fae777_3
  - re2=2024.07.02=h9925aae_3
  - readline=8.2=h8c095d6_2
  - referencing=0.36.2=pyh29332c3_0
  - requests=2.32.4=py312h06a4308_0
  - rpds-py=0.24.0=py312h3b7be25_0
  - ruptures=1.1.10=py312h4f23490_0
  - s2n=1.5.17=hba75a32_0
  - scikit-learn=1.6.1=py312h6a678d5_0
  - scipy=1.15.2=py312ha707e6e_0
  - sdl2=2.32.54=h3f2d84a_0
  - sdl2_image=2.8.2=h06ee604_1
  - sdl2_mixer=2.6.3=h8830914_1
  - sdl2_ttf=2.24.0=hc1d668e_1
  - sdl3=3.2.12=he3e324a_2
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - setuptools=80.1.0=pyhff2d567_0
  - six=1.17.0=pyhd8ed1ab_0
  - smmap=5.0.2=pyhd8ed1ab_0
  - snappy=1.2.1=h8bd8927_1
  - soupsieve=2.5=pyhd8ed1ab_1
  - statsmodels=0.14.6=py312h4f23490_0
  - streamlit=1.46.0=py312h06a4308_0
  - svt-av1=3.1.2=hecca717_0
  - sympy=1.14.0=pyh2585a3b_105
  - ta=0.11.0=pyhd8ed1ab_1
  - ta-lib=0.5.1=py312h66e93f0_0
  - tenacity=9.1.2=pyhd8ed1ab_0
  - threadpoolctl=3.5.0=py312he106c6f_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_1
  - tornado=6.5.1=py312h5eee18b_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - typing-extensions=4.13.2=h0e9735f_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h78e105d_0
  - unicodedata2=16.0.0=py312h66e93f0_0
  - urllib3=2.4.0=pyhd8ed1ab_0
  - watchdog=6.0.0=py312h7900ff3_0
  - wayland=1.23.1=h3e06ad9_1
  - webencodings=0.5.1=pyhd8ed1ab_3
  - wheel=0.45.1=pyhd8ed1ab_1
  - xcb-util=0.4.1=hb711507_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.44=hb9d3cd8_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxcomposite=0.4.6=hb9d3cd8_2
  - xorg-libxcursor=1.2.3=hb9d3cd8_0
  - xorg-libxdamage=1.1.6=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=hb9d3cd8_0
  - xorg-libxfixes=6.0.1=hb9d3cd8_0
  - xorg-libxi=1.8.2=hb9d3cd8_0
  - xorg-libxrandr=1.5.4=hb9d3cd8_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xorg-libxscrnsaver=1.2.4=hb9d3cd8_0
  - xorg-libxtst=1.2.5=hb9d3cd8_3
  - xorg-libxxf86vm=1.1.6=hb9d3cd8_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - yaml=0.2.5=h7f98852_2
  - yfinance=0.2.58=pyhd8ed1ab_0
  - zipp=3.21.0=pyhd8ed1ab_1
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py312h66e93f0_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - kaleido==0.2.1
prefix: /usr/prog/miniconda/envs/talib_yf_pygame
